# Generated by Django 4.2.20 on 2025-03-11 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tea_type",
                    models.CharField(
                        choices=[
                            ("煎茶", "煎茶"),
                            ("玉露", "玉露"),
                            ("抹茶", "抹茶"),
                            ("ほうじ茶", "ほうじ茶"),
                        ],
                        max_length=50,
                        verbose_name="茶葉の種類",
                    ),
                ),
                ("production_date", models.DateField(verbose_name="生産日")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="生産量(kg)"
                    ),
                ),
                (
                    "quality_check",
                    models.CharField(
                        choices=[("A級", "A級"), ("B級", "B級"), ("C級", "C級")],
                        max_length=50,
                        verbose_name="品質評価",
                    ),
                ),
                (
                    "quality_notes",
                    models.TextField(blank=True, null=True, verbose_name="品質メモ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登録日時"
                    ),
                ),
            ],
            options={
                "verbose_name": "生産データ",
                "verbose_name_plural": "生産データ",
                "ordering": ["-production_date"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_date", models.DateField(verbose_name="出荷日")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="出荷量(kg)"
                    ),
                ),
                ("customer_name", models.CharField(max_length=100, verbose_name="顧客名")),
                (
                    "customer_contact",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="連絡先"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登録日時"
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tea_production.production",
                        verbose_name="生産データ",
                    ),
                ),
            ],
            options={
                "verbose_name": "出荷データ",
                "verbose_name_plural": "出荷データ",
                "ordering": ["-shipment_date"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="在庫量(kg)"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最終更新"),
                ),
                (
                    "production",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tea_production.production",
                        verbose_name="生産データ",
                    ),
                ),
            ],
            options={
                "verbose_name": "在庫データ",
                "verbose_name_plural": "在庫データ",
                "ordering": ["-last_updated"],
            },
        ),
    ]
